# Generated by Django 3.1.7 on 2021-03-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ipv6_prefix', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('execution_time', models.TimeField()),
                ('executor', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('in_use', models.BooleanField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.building')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vttag', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=15)),
                ('sdate', models.DateField()),
                ('manufacturer_model', models.CharField(max_length=255)),
                ('serial_number', models.PositiveBigIntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('classification', models.CharField(max_length=255)),
                ('custodian', models.CharField(max_length=255)),
                ('porder', models.CharField(max_length=255)),
                ('pdate', models.CharField(max_length=255)),
                ('pvalue', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('surplus', models.SmallIntegerField()),
                ('cnames', models.CharField(max_length=2048)),
                ('dept', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=128)),
                ('mailexhange', models.SmallIntegerField()),
                ('cstag', models.CharField(max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.building')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.history')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.ip')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkoutdate', models.DateField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.personalid')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.equipment')),
            ],
        ),
    ]
