# Generated by Django 3.1.7 on 2021-04-10 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210407_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='sdate',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='surplus',
        ),
        migrations.AddField(
            model_name='equipment',
            name='acquistion_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='building',
            name='ipv6_prefix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkoutdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.personalid'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='equipment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.building'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='classification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cnames',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cstag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='custodian',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='dept',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='history',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.history'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ip',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.ip'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mailexhange',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pdate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='porder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pvalue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vttag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='command',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='execution_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='executor',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ip',
            name='address',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='ip',
            name='building',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.building'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
