# Generated by Django 3.1.7 on 2021-04-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210411_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='cstag',
            new_name='cs_tag',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='mailexhange',
            new_name='mail_exchange',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='pdate',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='porder',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='pvalue',
            new_name='purchase_value',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='vttag',
            new_name='vt_tag',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='cnames',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='history',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ip',
        ),
        migrations.AddField(
            model_name='history',
            name='equipment',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, to='inventory.equipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ip',
            name='ip_type',
            field=models.CharField(choices=[('I4', 'IPv4'), ('I6', 'IPv6')], default='I4', max_length=2),
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('aliases', models.CharField(blank=True, max_length=255)),
                ('building', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.building')),
                ('ipv4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='IPv4', to='inventory.ip')),
                ('ipv6', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='IPv6', to='inventory.ip')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.hostname'),
        ),
    ]
