# Generated by Django 3.1.7 on 2021-04-12 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210411_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostname',
            name='ipv4',
        ),
        migrations.RemoveField(
            model_name='hostname',
            name='ipv6',
        ),
        migrations.AddField(
            model_name='equipment',
            name='ipv4',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='IPv4', to='inventory.ip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='ipv6',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='IPv6', to='inventory.ip'),
            preserve_default=False,
        ),
    ]
