# Generated by Django 3.1.7 on 2021-04-12 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210412_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostname',
            name='ipv4',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='HostnameIPv4', to='inventory.ip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostname',
            name='ipv6',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='HostnameIPv6', to='inventory.ip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ipv4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EquipmentIPv4', to='inventory.ip'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ipv6',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='EquipmentIPv6', to='inventory.ip'),
        ),
    ]
