# Generated by Django 3.1.7 on 2021-04-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210415_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
