# Generated by Django 3.1.7 on 2021-04-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210412_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='ipv4',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ipv6',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='mail_exchange',
        ),
    ]
