# Generated by Django 3.1.7 on 2021-04-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210414_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
