# Generated by Django 3.1.7 on 2021-04-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210417_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostname',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
