# Generated by Django 3.1.7 on 2021-04-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210418_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='mail_exchange',
            field=models.SmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkoutdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='execution_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
