# Generated by Django 3.1.7 on 2021-04-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210418_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostname',
            name='in_use',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
