# Generated by Django 3.1.7 on 2021-04-19 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_hostname_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.building'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Hostname', to='inventory.hostname'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mail_exchange',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='MailExchangeHostname', to='inventory.hostname'),
        ),
        migrations.CreateModel(
            name='InventoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pid', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='checkout',
            name='contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.inventoryuser'),
        ),
        migrations.DeleteModel(
            name='PersonalID',
        ),
    ]
