# Generated by Django 3.1.7 on 2021-04-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210419_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryuser',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
