# Generated by Django 3.1.7 on 2021-04-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210419_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='inventoryuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='inventoryuser',
            name='last_name',
        ),
    ]
