# Generated by Django 3.1.7 on 2021-04-28 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0014_auto_20210419_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='ipv6_prefix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IPv6 Prefix'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkoutdate',
            field=models.DateField(auto_now_add=True, verbose_name='Checkout Date'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.inventoryuser', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='equipment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.equipment', verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.building', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='classification',
            field=models.CharField(blank=True, max_length=255, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cs_tag',
            field=models.CharField(blank=True, max_length=255, verbose_name='CS Tag'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='custodian',
            field=models.CharField(blank=True, max_length=255, verbose_name='Custodian'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='dept',
            field=models.CharField(blank=True, max_length=10, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Hostname', to='inventory.hostname', verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mail_exchange',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='MailExchangeHostname', to='inventory.hostname', verbose_name='Mail Exchange'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer_model',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manufacturer/Model'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=255, verbose_name='Purchase Order'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Purchase Value'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, max_length=15, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, max_length=128, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vt_tag',
            field=models.CharField(blank=True, max_length=255, verbose_name='VT Tag'),
        ),
        migrations.AlterField(
            model_name='history',
            name='command',
            field=models.CharField(blank=True, max_length=255, verbose_name='Command'),
        ),
        migrations.AlterField(
            model_name='history',
            name='equipment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.equipment', verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='history',
            name='execution_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Execution Time'),
        ),
        migrations.AlterField(
            model_name='history',
            name='executor',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Executor'),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='aliases',
            field=models.CharField(blank=True, max_length=255, verbose_name='Aliases'),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='building',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.building', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='hostname',
            field=models.CharField(max_length=255, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='in_use',
            field=models.BooleanField(verbose_name='In Use'),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='ipv4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='HostnameIPv4', to='inventory.ip', verbose_name='IPv4'),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='ipv6',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='HostnameIPv6', to='inventory.ip', verbose_name='IPv6'),
        ),
        migrations.AlterField(
            model_name='inventoryuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='inventoryuser',
            name='pid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PID'),
        ),
        migrations.AlterField(
            model_name='inventoryuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='address',
            field=models.CharField(blank=True, max_length=40, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='building',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.building', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='in_use',
            field=models.BooleanField(verbose_name='In Use'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip_type',
            field=models.CharField(choices=[('I4', 'IPv4'), ('I6', 'IPv6')], default='I4', max_length=2, verbose_name='IP Type'),
        ),
    ]
