# Generated by Django 3.1.7 on 2021-04-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20210419_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip_type',
            field=models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], default='IPv4', max_length=4),
        ),
    ]
