# Generated by Django 3.1.7 on 2021-04-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20210428_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='ipv4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HostnameIPv4', to='inventory.ip', verbose_name='IPv4'),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='ipv6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HostnameIPv6', to='inventory.ip', verbose_name='IPv6'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip_type',
            field=models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], default='IPv4', max_length=5, verbose_name='IP type'),
        ),
    ]
