# Generated by Django 3.1.7 on 2021-04-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20210428_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip_type',
            field=models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], default='IPv4', max_length=5, verbose_name='IP type'),
        ),
    ]
