# Generated by Django 3.1.7 on 2021-04-30 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20210430_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='mail_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='MailExchangeHostname', to='inventory.hostname', verbose_name='Mail exchange'),
        ),
    ]
