# Generated by Django 3.1.7 on 2021-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20210430_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Purchase value'),
        ),
    ]
