# Generated by Django 3.1.7 on 2021-04-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20210430_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Hostname', to='inventory.hostname', verbose_name='Hostname'),
        ),
    ]
