# Generated by Django 3.1.7 on 2021-04-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20210430_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='classification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cs_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CS tag'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='custodian',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custodian'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='dept',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Hostname', to='inventory.hostname', verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer/Model'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase order'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vt_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VT tag'),
        ),
    ]
