# Generated by Django 3.1.7 on 2021-05-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20210430_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='classification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cs_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CS tag'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='custodian',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custodian'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer/Model'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase order'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vt_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VT tag'),
        ),
    ]
